# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
    reviewers: [ajayyy]
    assignees: [ajayyy]

  - package-ecosystem: npm
    directory: /
    schedule: {interval: weekly}
    reviewers: [ajayyy]
    assignees: [ajayyy]
